version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/stream-apps"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer"
    directory: "/docker-compose"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
