repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: pretty-format-json
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
- repo: https://github.com/dustinsand/pre-commit-jvm
  rev: v0.6.0
  hooks:
  - id: google-java-formatter-jdk11
    args: [--replace, --set-exit-if-changed]
