/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spark.streamer;

import org.junit.Test;
import spark.stream.runners.KafkaToConsole;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        KafkaToConsole classUnderTest = new KafkaToConsole();
        assertNotNull("app should have a greeting", classUnderTest.toString());
    }
}
